name: bmta_rfid_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter_riverpod: ^2.3.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.9.0
  riverpod: ^2.3.0
  equatable: ^2.0.7
  dio: ^5.7.0
  tuple: ^2.0.0
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  flutter_localization: ^0.3.2
  # zebra123: ^4.0.0
  month_year_picker: ^0.4.0+1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.12
  dropdown_textfield: ^1.2.0
  quickalert: ^1.1.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4
  zebra123:
    path: ../bmta_RFID/zebra123  # ชี้ไปยัง plugin ที่คุณสร้างไว้
  permission_handler: ^12.0.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  # plugin:
  #   platforms:
  #     android:
  #       package: com.example.bmta_rfid_app
  #       pluginClass: Zebra123

  uses-material-design: true

  

  assets:
  - lib/assets/icons/
  - lib/assets/images/
  - lib/assets/fonts/

  fonts:
    - family: THSarabunNew
      fonts:
        - asset: lib/assets/fonts/THSarabunNew.ttf
    - family: Kanit
      fonts:
        - asset: lib/assets/fonts/Kanit/Kanit-Regular.ttf
