name: bmta
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  zebra_rfid_reader_sdk:
  # When depending on this package from a real application you should use:
  #   pda_rfid_scanner: ^x.y.z
  # See https://dart.dev/tools/pub/dependencies#version-constraints
  # The example app is bundled with the plugin so we use a path dependency on
  # the parent directory to use the current plugin's version.
    path: ../

  flutter_localizations:
    sdk: flutter  
  intl: any  

  flutter_gen: ^5.10.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  dio: ^5.7.0
  dropdown_textfield: ^1.2.0
  # file_picker: ^8.1.2
  connectivity_plus: ^6.1.3
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  
  json_annotation: ^4.9.0
  quickalert: ^1.1.0
  tuple: ^2.0.0
  shimmer: ^2.0.0
  month_year_picker: ^0.4.0+1
  flutter_secure_storage: ^9.2.2
  cross_file: ^0.3.4+2
  mime: ^1.0.6
 
  intl_utils: ^2.8.7
  flutter_html: ^3.0.0-beta.2
  mobile_scanner: ^7.0.0-beta.3
  rflutter_alert: ^2.0.7
  web_socket_channel: ^2.1.0
  animated_snack_bar: ^0.4.0
  url_launcher: ^6.3.0
  photo_view: ^0.15.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  # qr_code_scanner: ^1.0.1
  qr_scanner_overlay: ^0.0.2
  dropdown_search: ^6.0.1
  easy_debounce: ^2.0.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  share_plus: ^10.1.0
  # uni_links: ^0.5.1
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  path_provider: ^2.1.4
  # image_gallery_saver: ^2.0.3
  open_filex: ^4.5.0
  image_cropper: ^8.0.2
  camera: ^0.11.0+2
  local_auth: ^2.3.0
  shared_preferences: ^2.3.3
  package_info_plus: ^8.1.1
  value_layout_builder: ^0.4.0
  flutter_screenutil: ^5.9.3
  otp_autofill: ^4.1.0
  collection: ^1.17.1
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  logger: ^2.5.0
  qr_code_vision: ^0.1.2
  flutter_web_file_selector: ^0.3.1
  qr_code_scanner_plus: ^2.0.6
  flutter_web_qrcode_scanner: ^1.1.1
  # flutter_local_notifications: ^18.0.1
  # flutter_app_badger: ^1.5.0
  flutter_app_badge_control: ^0.0.2
  change_app_package_name: ^1.4.0



  nb_utils: ^7.1.3
  persistent_bottom_nav_bar: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: "^0.14.3"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - .env
    - lib/assets/images/
    - lib/assets/icons/

  fonts:
  - family: THSarabunNew
    fonts:
      - asset: lib/assets/fonts/THSarabunNew.ttf
  - family: Kanit
    fonts:
      - asset: lib/assets/fonts/Kanit/Kanit-Thin.ttf
        weight: 100
      - asset: lib/assets/fonts/Kanit/Kanit-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: lib/assets/fonts/Kanit/Kanit-ExtraLight.ttf
        weight: 200
      - asset: lib/assets/fonts/Kanit/Kanit-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: lib/assets/fonts/Kanit/Kanit-Light.ttf
        weight: 300
      - asset: lib/assets/fonts/Kanit/Kanit-LightItalic.ttf
        weight: 300
        style: italic
      - asset: lib/assets/fonts/Kanit/Kanit-Regular.ttf
        weight: 400
      - asset: lib/assets/fonts/Kanit/Kanit-Italic.ttf
        weight: 400
        style: italic
      - asset: lib/assets/fonts/Kanit/Kanit-Medium.ttf
        weight: 500
      - asset: lib/assets/fonts/Kanit/Kanit-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: lib/assets/fonts/Kanit/Kanit-SemiBold.ttf
        weight: 600
      - asset: lib/assets/fonts/Kanit/Kanit-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: lib/assets/fonts/Kanit/Kanit-Bold.ttf
        weight: 700
      - asset: lib/assets/fonts/Kanit/Kanit-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: lib/assets/fonts/Kanit/Kanit-ExtraBold.ttf
        weight: 800
      - asset: lib/assets/fonts/Kanit/Kanit-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: lib/assets/fonts/Kanit/Kanit-Black.ttf
        weight: 900
      - asset: lib/assets/fonts/Kanit/Kanit-BlackItalic.ttf
        weight: 900
        style: italic
  generate: true  


flutter_localizations:
  arb-dir: lib/l10n
  template-arb-file: intl_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_logo_bmta_staff.png"



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
